### ISSUE TITLE
Stack size editor and Energymanager dont work after updated LDB tool

### ISSUE THREAD

**Issue by Valoneu** [WaGi-Coding/Taki_DSP-Mods#8]
TITLE

**Comment by Gabesz850110** [comment]
I also would like to ask, to pleas update your awesome mods, I realy liked them, but now doesn't working any of them.

**Comment by Valoneu** [comment]
> 

i updated energy manager in my FactoryOverclock mod and for stack size you can use the one by appuns

**Comment by Valoneu** [comment]
i asked him on discord if he gonna update and he said he needs to fix RL and then maybe

**Comment by Gabesz850110** [comment]
Factory overclock is a nice mod, but a bit too cheaty for me. Not my type, despite Energy Manager also cheaty a bit.
I Enjoyed the simplicity of Stack size with the ingame GUI and energymanager with a single .cfg file setup.

I don't know what is RL, but I still waiting for theese mods to be updated.

**Comment by Gabesz850110** [comment]
Free foundations, free soil also not working BTW.

**Comment by Valoneu** [comment]
RL is real life
